tweens = [

    "0 - Linear",
    "1 - Easing Out",
    "2 - Easing In",
    "3 - Quad In",
    "4 - Quad Out",
    "5 - Quad In / Out",
    "6 - Cubic In",
    "7 - Cubic Out",
    "8 - Cubic In / Out",
    "9 - Quart In",
    "10 - Quart Out",
    "11 - Quart In / Out",
    "12 - Quint In",
    "13 - Quint Out",
    "14 - Quint In / Out",
    "15 - Sine In",
    "16 - Sine Out",
    "17 - Sine In / Out",
    "18 - Expo In",
    "19 - Expo Out",
    "20 - Expo In / Out",
    "21 - Circ In",
    "22 - Circ Out",
    "23 - Circ In / Out",
    "24 - Elastic In",
    "25 - Elastic Out",
    "26 - ElasticHalf Out",
    "27 - ElasticQuarter Out",
    "28 - Elastic In / Out",
    "29 - Back In",
    "30 - Back Out",
    "31 - BackIn / Out",
    "32 - Bounce In",
    "33 - Bounce Out",
    "34 - Bounce In / Out"
]
